# Generated by Django 4.0 on 2023-11-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=65)),
                ('colour', models.CharField(max_length=65)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
